### ISSUE TITLE
Crashing when going west from ballroom

### ISSUE THREAD

**Issue by TanyaXfun** [seit-gruppe14/world-of-oop#15]
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.remove(ArrayList.java:492)
    at zuulFramework.worldofzuul.Monster.timeCallback(Monster.java:110)
    at zuulFramework.worldofzuul.Time.doTimeEvent(Time.java:72)
    at zuulFramework.worldofzuul.Time.updateTime(Time.java:109)
    at zuulFramework.worldofzuul.Game.updateTime(Game.java:547)
    at zuulFramework.worldofzuul.Ballroom.doSpecialEvent(Ballroom.java:25)
    at zuulFramework.worldofzuul.Game.goRoom(Game.java:268)
    at zuulFramework.worldofzuul.Game.processCommand(Game.java:209)
    at zuulFramework.worldofzuul.Game.play(Game.java:150)
    at zuul.Zuul.main(Zuul.java:16)
C:\Users\thananya\Documents\world-of-oop\nbproject\build-impl.xml:1050: The following error occurred while executing this line:
C:\Users\thananya\Documents\world-of-oop\nbproject\build-impl.xml:804: Java returned: 1
BUILD FAILED (total time: 57 seconds)

**Comment by zlepper** [comment]
This happens because when monster gets the number of items in a room, it actually looks at the number of items in it's inventory. 
Specifically line line 111.

**Comment by Hugzy** [comment]
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.remove(ArrayList.java:492)
    at zuulFramework.worldofzuul.Monster.timeCallback(Monster.java:110)
    at zuulFramework.worldofzuul.Time.doTimeEvent(Time.java:72)
    at zuulFramework.worldofzuul.Time.updateTime(Time.java:109)
    at zuulFramework.worldofzuul.Game.goRoom(Game.java:265)
    at zuulFramework.worldofzuul.Game.processCommand(Game.java:209)
    at zuulFramework.worldofzuul.Game.play(Game.java:150)
    at zuul.Zuul.main(Zuul.java:16)

**Comment by zlepper** [comment]
Fixed
